### ISSUE TITLE
Production ready?

### ISSUE THREAD

**Issue by thebylito** [geckosio/phaser3-multiplayer-game-example#1]
Very nice work! Development works soo good!

can you provide steps for publish?(ex heroku)
i have changed ports, but doesnt work

https://onlinegamee1.herokuapp.com

example repo: https://github.com/thebylito/multiplayer-game-js

**Comment by yandeu** [comment]
It does not work on heroku since this example is using [geckos.io](https://github.com/geckosio/geckos.io#readme) which is using webrtc which uses random ports on UPD. Read more about this in the [deployment section of geckos.io](https://github.com/geckosio/geckos.io#deployment).

To make it work on heroku, you would have to use something like socket.io. See my other [multiplayer game example](https://github.com/yandeu/phaser3-multiplayer-with-physics#readme).
